mod attribute;
mod choice;
mod complex_content;
mod complex_type;
mod element;
mod list;
mod parser;
mod sequence;
mod simple_content;
mod simple_type;
mod tests;
mod utils;
mod xsd_elements;
pub mod constants;
pub mod types;
pub use parser::*;
