mod attribute;
mod choice;
mod complex_content;
mod complex_type;
mod constants;
mod element;
mod parser;
mod sequence;
mod simple_content;
mod simple_type;
mod tests;
mod types;
mod utils;
mod xsd_elements;
pub use parser::*;
